### ISSUE TITLE
PIP PIP Cheerio - Issues installing deeplabcut with pip 

### ISSUE THREAD

**Issue by jpweinrich** [DeepLabCut/DeepLabCut#118]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Windows 10, with an Anaconda Env, & DeepLabCut 2.0.

**Describe the problem**

I'm having trouble doing the pip installation of deeplab cut. I have pandas, however it uninstalls it, tries to reinstall it, and then fails. I've attached all of the text from the terminal during installation. I wish this was easier!
[piperror.txt](https://github.com/AlexEMG/DeepLabCut/files/2591364/piperror.txt)

**Comment by MMathisLab** [comment]
did you try installing pandas separately? Sorry, we tried our best to make it easy for you.... you could try pip install --ignore-installed deeplabcut, then it will ignore the pandas you already have installed. It seems an issue with you visual studio/pandas

**Comment by AlexEMG** [comment]
Perhaps, please try out this conda environment for Windows: https://github.com/AlexEMG/DeepLabCut/issues/112

**Comment by MMathisLab** [comment]
I haven't heard back, so I will assume this is fixed. There is also a new release: pip install deeplabcut==2.0.0.dev7

**Comment by jpweinrich** [comment]
Hi, thanks for the quick response! I was able to carve out some time today to work on this, so I'll let you know how it goes. I'm setting aside a few hours a week to get this up and running, so I may not respond immediately. 

As an update, I tried running the updated pip installation and it still failed. I'm going to give the windows environment a try now. 

This is definitely not closed though!

**Comment by MMathisLab** [comment]
great, feel free to join the Slack group too, for a faster back and forth if needed!

**Comment by jpweinrich** [comment]
Will do, just emailed for an invitation. Thanks!

Running the instructions from #20 now.

**Comment by jpweinrich** [comment]
That worked very well, definitely recommend having that as the default installation method  for Windows. Thanks!
