### ISSUE TITLE
Training doesn't reach first iteration -- due to CUDA/TF version mismatch causes by pinned numpy

### ISSUE THREAD

**Issue by bgibWh** [DeepLabCut/DeepLabCut#1487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Training starts and appears to recognize GPU but never reaches first iteration and GPU levels on task manager stay around 0-2%. It also doesn't seem to engage the CPU as leaving it 'training' overnight still doesn't have any iterations so it's not just working slow. Only encountered this issue when I updated my deeplabcut setup from the original DLC-GPU to the new version (DLC 2.2.0.1)

### Operating System

Windows 10.0.18362
python 3.8
CUDA 11.0

### DeepLabCut version

dlc version= 2.2.0.1

### DeepLabCut mode

single animal

### Device type

GeForce RTX 2080 SUPER

### Steps To Reproduce

1. Go to Envs of anaconda navigator and open DEEPLABCUT with ipython
2. import deeplabcut (2021-08-31 10:59:50.660626: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll)
3. Train network with previously labeled data from older DLC [deeplabcut.train_network('config path\\config.yaml', shuffle=1,trainingsetindex=0,gputouse=0,max_snapshots_to_keep=5, displayiters=1000,saveiters=20000, maxiters=500000)]

### Relevant log output

```shell
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]],
 'all_joints_names': ['snout',
                      'MLA',
                      'MLB',
                      'MLC',
                      'MLD',
                      'MLE',
                      'MLF',
                      'MLG',
                      'MLH',
                      'tail'],
 'alpha_r': 0.02,
 'batch_size': 1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Redfish1Aug26\\Redfish1_Brendan95shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\brendan.gibbs\\Anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Redfish1Aug26\\Documentation_data-Redfish1_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 10,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'E:\\Clark\\DLC\\Redfish1-Brendan-2021-08-26',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'E:\\Clark\\DLC\\Redfish1-Brendan-2021-08-26\\dlc-models\\iteration-0\\Redfish1Aug26-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
2021-08-31 10:11:15.230163: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-08-31 10:11:15.258784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 SUPER computeCapability: 7.5
coreClock: 1.815GHz coreCount: 48 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 462.00GiB/s
2021-08-31 10:11:15.264023: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-08-31 10:11:15.268884: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-08-31 10:11:15.272500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-08-31 10:11:15.274994: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-08-31 10:11:15.280126: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-08-31 10:11:15.284042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-08-31 10:11:15.301054: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-08-31 10:11:15.302771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
Loading ImageNet-pretrained resnet_50
2021-08-31 10:11:15.624581: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-08-31 10:11:15.633575: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2165c163ed0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-08-31 10:11:15.636982: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-08-31 10:11:15.639095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 SUPER computeCapability: 7.5
coreClock: 1.815GHz coreCount: 48 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 462.00GiB/s
2021-08-31 10:11:15.649358: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2021-08-31 10:11:15.651396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2021-08-31 10:11:15.654049: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2021-08-31 10:11:15.656027: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2021-08-31 10:11:15.662028: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2021-08-31 10:11:15.664015: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2021-08-31 10:11:15.666403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-08-31 10:11:15.668299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-08-31 10:11:17.467402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-31 10:11:17.469720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2021-08-31 10:11:17.471127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2021-08-31 10:11:17.472848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6198 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-08-31 10:11:17.480107: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2167e743b70 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-08-31 10:11:17.482466: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 SUPER, Compute Capability 7.5
Max_iters overwritten as 500000
Display_iters overwritten as 1000
Save_iters overwritten as 50000
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'E:\\Clark\\DLC\\Redfish1-Brendan-2021-08-26\\dlc-models\\iteration-0\\Redfish1Aug26-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]], 'all_joints_names': ['snout', 'MLA', 'MLB', 'MLC', 'MLD', 'MLE', 'MLF', 'MLG', 'MLH', 'tail'], 'alpha_r': 0.02, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Redfish1Aug26\\Redfish1_Brendan95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'init_weights': 'C:\\Users\\brendan.gibbs\\Anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Redfish1Aug26\\Documentation_data-Redfish1_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 10, 'pos_dist_thresh': 17, 'project_path': 'E:\\Clark\\DLC\\Redfish1-Brendan-2021-08-26', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
```

### Anything else?
```
Tue Aug 31 10:52:47 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 451.48       Driver Version: 451.48       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208... WDDM  | 00000000:01:00.0  On |                  N/A |
| 18%   32C    P8    14W / 250W |    735MiB /  8192MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       996    C+G   ...bbwe\Microsoft.Photos.exe    N/A      |
|    0   N/A  N/A      1428    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      2780    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      6096    C+G   ...es.TextInput.InputApp.exe    N/A      |
|    0   N/A  N/A      8712    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A      8912    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      9480    C+G   ...w5n1h2txyewy\SearchUI.exe    N/A      |
|    0   N/A  N/A      9612    C+G   ...root\Office16\WINWORD.EXE    N/A      |
|    0   N/A  N/A     10216    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     12416    C+G   ...t\Teams\current\Teams.exe    N/A      |
|    0   N/A  N/A     13216    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     15476    C+G   ...obeNotificationClient.exe    N/A      |
|    0   N/A  N/A     16904    C+G   ...wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A     17320    C+G   ...t\Teams\current\Teams.exe    N/A      |
+-----------------------------------------------------------------------------+
```
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
This line:

>` import deeplabcut (2021-08-31 10:59:50.660626: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll)`

suggests that you don't have all of the proper parts for CUDA 11 (it's using a 10.1 library).  In that case, your training is running on your CPU, not your GPU, and it could take a while to run 1000 iterations  (your `display_iters`) before showing anything.

To fix, I suggest the following:
1. As per the full [installation instructions](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md),  under **GPU support**, activate your env, and run `conda install -c conda-forge cudnn`. That should fix the initial problem (that message should show something like `cudart64_11.dll`).
2. Start your training again, but change `display_iters` to something like 1 or 10.  That way you'll get faster feedback to ensure that training is actually happening, and the code isn't stuck before it starts running iterations.
3. To see if your GPU is really being used, the best way on windows is to look at the GPU memory on the "Performance" tab of Windows task manager (see discussion [here](https://github.com/DeepLabCut/DeepLabCut/issues/1485#issuecomment-909174928)). You have only 8GB of GPU memory, and a training session should probably take most of that (depending on image size, batch size, etc). GPU memory gets allocated when training starts, and stays high during training. You can also look at the CUDA performance there, which for me oscillates up and down during training.

**Comment by bgibWh** [comment]
I just ran `conda install -c conda-forge cudnn` and I also added the correct CUDnn components to the CUDA 11 (cudnn64_8.dll; cudnn.h; cudnn.lib) but it still seems like it's trying to use CUDA 10.1 as I still get the line `Successfully opened dynamic library cudart64_101.dll` after importing deeplabcut to ipython

**Comment by backyardbiomech** [comment]
I just now updated a 2.2rc3 env to 2.2.0.1 (from the repo) on my windows machine with a GPU.
Unfortunately, I don't get the "Successfully opened...dll" messages (I may have muted them somehow?), but the testscript definitely engaged my GPU.

In case it helps the output of my env for `conda list` is below:

<details>

```
# Name                    Version                   Build  Channel
absl-py                   0.13.0                   pypi_0    pypi
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.0.0              pyhd8ed1ab_0    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30                pypi_0    pypi
cffi                      1.14.6           py38hd8c33c5_0    conda-forge
charset-normalizer        2.0.4                    pypi_0    pypi
clang                     5.0                      pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cudatoolkit               11.2.2               h933977f_8    conda-forge
cudnn                     8.2.1.32             h754d62a_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
debugpy                   1.4.1            py38h885f38d_0    conda-forge
decorator                 4.4.2                    pypi_0    pypi
deeplabcut                2.2.0.1                  pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.5                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.39.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
icu                       68.1                 h0e60522_0    conda-forge
idna                      3.2                      pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.4                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        4.6.4            py38haa244fe_0    conda-forge
ipykernel                 6.2.0            py38h595d716_0    conda-forge
ipython                   7.26.0           py38h595d716_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.18.0           py38haa244fe_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py38haa244fe_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
keras                     2.6.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
llvmlite                  0.37.0                   pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py38h294d835_0    conda-forge
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mistune                   0.8.4           py38h294d835_1004    conda-forge
moviepy                   1.0.3                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
nb_conda                  2.2.1            py38haa244fe_4    conda-forge
nb_conda_kernels          2.3.1            py38haa244fe_0    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py38haa244fe_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.6.2                    pypi_0    pypi
notebook                  6.4.3              pyha770c72_0    conda-forge
numba                     0.54.0                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
opencv-python             4.5.3.56                 pypi_0    pypi
opencv-python-headless    4.5.3.56                 pypi_0    pypi
openssl                   1.1.1k               h8ffe710_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.2                    pypi_0    pypi
pandoc                    2.14.1               h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
patsy                     0.5.1                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.1                    pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
proglog                   0.1.9                    pypi_0    pypi
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
prompt_toolkit            3.0.19               hd8ed1ab_0    conda-forge
protobuf                  3.17.3                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
python                    3.8.10          h7840368_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   301              py38h294d835_0    conda-forge
pywinpty                  1.1.3            py38hd3f51b4_0    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.2.1           py38h09162b1_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.1.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.10.0             pyhd8ed1ab_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
ruamel-yaml               0.17.11                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.18.2                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                57.4.0           py38haa244fe_0    conda-forge
shapely                   1.7.1                    pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sqlite                    3.36.0               h8ffe710_0    conda-forge
statsmodels               0.12.2                   pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.6.0                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.11.1           py38haa244fe_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             2.2.0                    pypi_0    pypi
tifffile                  2021.8.8                 pypi_0    pypi
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.62.1                   pypi_0    pypi
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.6                   pypi_0    pypi
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.1            py38haa244fe_4    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
wxpython                  4.0.7.post2              pypi_0    pypi
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
```

</details>

Compare your cudatoolkit, cudnn, and tensorflow versions to that, since I know that works.

The output from `nvcc -V` is 

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:25:35_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0
```

and `nvidia-smi` shows ` Driver Version: 471.11       CUDA Version: 11.4` (my card is a Quadro RTX 6000, so driver will vary for your).

I just noticed that your driver is 451.*. I'm not sure about your card and driver, but there's a chance that your driver doesn't fully support tensorflow 2+ and CUDA 11+.  You should investigate updating your driver (or at least compatibility of your existing driver with the above).

**Comment by bgibWh** [comment]
I updated both my driver and Cuda to `NVIDIA-SMI 471.96       Driver Version: 471.96       CUDA Version: 11.4`
and I compared my entire `conda list` and the only differences are that `numpy =  1.21.2` `opencv-python-headless = 3.4.9.33` and `tensorboard = 2.2.2` `tensorflow = 2.2.0` `tensorflow estimator = 2.2.0`

When I try to update tensorflow to 2.6.0 I get the error message `deeplabcut 2.2.0.1 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.`

to reverse this I do `pip install --upgrade deeplabcut` which reverts tensorboard to  2.2.2 and tensorflow to 2.2.0

Lastly when I open ipython and try to import deeplabcut after this, I get the message `2021-08-31 17:14:26.086991: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-08-31 17:14:26.089265: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.` which is weird since I updated everything yet it's still looking for CUDA 10.1

**Comment by jeylau** [comment]
@bgibWh, that makes sense. Tensorflow 2.2 looks for cuda 10.1, whereas cuda>=11 only works for tf >= 2.3. The fix is to unpin numpy in setup.py, so it won't complain that tensorflow is trying to install numpy 1.19.5.

**Comment by MMathisLab** [comment]
unpinned numpy now you can install from git!: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-use-the-latest-updates-directly-from-github

**Comment by bgibWh** [comment]
I've installed via git but still get the message `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deeplabcut 2.2.0.1 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.` when I install tensorflow to match my CUDA `pip install tensorflow==2.4.1` 

It allows me to start training in ipython but my GPU usage on task manager is basically 0% while the dedicated memory usage of my GPU increases but I can leave it overnight for days without getting a single visible iteration. Not sure why but it just doesn't seem like my GPU is being fully utilized for training. Any help would be greatly appreciated

**Comment by backyardbiomech** [comment]
In your env, try:

```
pip install --upgrade --upgrade-strategy eager git+https://github.com/deeplabcut/deeplabcut.git
```

that should update numpy to 1.21, TF to 2.6, and deeplabcut to the latest master on GitHub.

**Comment by bgibWh** [comment]
I did that but still got the error message `deeplabcut 2.2.0.1 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.`

**Comment by bgibWh** [comment]
Here's everything I get when I did that:

 C:\Users\brendan.gibbs> pip install --upgrade --upgrade-strategy eager git+https://github.com/deeplabcut/deeplabcut.git
Collecting git+https://github.com/deeplabcut/deeplabcut.git
  Cloning https://github.com/deeplabcut/deeplabcut.git to c:\users\brendan.gibbs\appdata\local\temp\pip-req-build-42304u8y
  Running command git clone -q https://github.com/deeplabcut/deeplabcut.git 'C:\Users\brendan.gibbs\AppData\Local\Temp\pip-req-build-42304u8y'
  Resolved https://github.com/deeplabcut/deeplabcut.git to commit 51fd9fc33f0cb96e165fa22367bde84b87e350c2
Requirement already satisfied: ipython in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (7.27.0)
Requirement already satisfied: filterpy in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (1.4.5)
Requirement already satisfied: ruamel.yaml>=0.15.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (0.17.16)
Requirement already satisfied: imgaug>=0.4.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (0.4.0)
Requirement already satisfied: numba in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (0.53.1)
Collecting numba
  Using cached numba-0.54.0-cp38-cp38-win_amd64.whl (2.3 MB)
Requirement already satisfied: matplotlib in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (3.4.3)
Requirement already satisfied: networkx in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (2.6.3)
Requirement already satisfied: numpy in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (1.19.5)
Collecting numpy
  Using cached numpy-1.21.2-cp38-cp38-win_amd64.whl (14.0 MB)
Requirement already satisfied: opencv-python-headless in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (4.5.3.56)
Requirement already satisfied: pandas>=1.0.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (1.3.2)
Requirement already satisfied: scikit-image>=0.17 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (0.18.3)
Requirement already satisfied: scikit-learn in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (0.24.2)
Requirement already satisfied: scipy>=1.4 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (1.4.1)
Collecting scipy>=1.4
  Using cached scipy-1.7.1-cp38-cp38-win_amd64.whl (33.7 MB)
Requirement already satisfied: statsmodels>=0.11 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (0.12.2)
Requirement already satisfied: tables in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (3.6.1)
Requirement already satisfied: tensorflow>=2.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (2.4.1)
Collecting tensorflow>=2.0
  Using cached tensorflow-2.6.0-cp38-cp38-win_amd64.whl (423.2 MB)
Requirement already satisfied: tensorpack in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (0.11)
Requirement already satisfied: tf_slim in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (1.1.0)
Requirement already satisfied: tqdm in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (4.62.2)
Requirement already satisfied: moviepy in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (1.0.3)
Requirement already satisfied: pyyaml in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (5.4.1)
Requirement already satisfied: Pillow>=7.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from deeplabcut==2.2.0.1) (8.3.2)
Requirement already satisfied: six in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from imgaug>=0.4.0->deeplabcut==2.2.0.1) (1.15.0)
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: imageio in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from imgaug>=0.4.0->deeplabcut==2.2.0.1) (2.9.0)
Requirement already satisfied: opencv-python in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from imgaug>=0.4.0->deeplabcut==2.2.0.1) (4.5.3.56)
Requirement already satisfied: Shapely in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from imgaug>=0.4.0->deeplabcut==2.2.0.1) (1.7.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from pandas>=1.0.1->deeplabcut==2.2.0.1) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from pandas>=1.0.1->deeplabcut==2.2.0.1) (2.8.2)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ruamel.yaml>=0.15.0->deeplabcut==2.2.0.1) (0.2.6)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from scikit-image>=0.17->deeplabcut==2.2.0.1) (2021.8.30)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from scikit-image>=0.17->deeplabcut==2.2.0.1) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from matplotlib->deeplabcut==2.2.0.1) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from matplotlib->deeplabcut==2.2.0.1) (1.3.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from matplotlib->deeplabcut==2.2.0.1) (2.4.7)
Requirement already satisfied: patsy>=0.5 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from statsmodels>=0.11->deeplabcut==2.2.0.1) (0.5.1)
Requirement already satisfied: absl-py~=0.10 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (0.13.0)
Requirement already satisfied: opt-einsum~=3.3.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (3.3.0)
Requirement already satisfied: astunparse~=1.6.3 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (1.6.3)
Requirement already satisfied: tensorboard~=2.6 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (2.6.0)
Collecting clang~=5.0
  Using cached clang-5.0-py3-none-any.whl
Requirement already satisfied: wheel~=0.35 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (0.37.0)
Collecting h5py~=3.1.0
  Using cached h5py-3.1.0-cp38-cp38-win_amd64.whl (2.7 MB)
Requirement already satisfied: termcolor~=1.1.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (1.1.0)
Collecting gast==0.4.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: flatbuffers~=1.12.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (1.12)
Collecting grpcio<2.0,>=1.37.0
  Using cached grpcio-1.40.0-cp38-cp38-win_amd64.whl (3.2 MB)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (1.12.1)
Collecting tensorflow-estimator~=2.6
  Using cached tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
Collecting keras~=2.6
  Using cached keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: keras-preprocessing~=1.1.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (1.1.2)
Requirement already satisfied: google-pasta~=0.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (0.2.0)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (3.17.3)
Requirement already satisfied: typing-extensions~=3.7.4 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorflow>=2.0->deeplabcut==2.2.0.1) (3.7.4.3)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (58.0.4)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (1.8.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (3.3.4)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (0.6.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (2.26.0)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (2.0.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (1.35.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (0.4.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (4.2.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (1.26.6)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (2021.5.30)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow>=2.0->deeplabcut==2.2.0.1) (3.1.1)
Requirement already satisfied: colorama in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (0.4.4)
Requirement already satisfied: backcall in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (3.0.20)
Requirement already satisfied: jedi>=0.16 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (0.18.0)
Requirement already satisfied: traitlets>=4.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (5.1.0)
Requirement already satisfied: matplotlib-inline in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (0.1.3)
Requirement already satisfied: pygments in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (2.10.0)
Requirement already satisfied: pickleshare in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (0.7.5)
Requirement already satisfied: decorator in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from ipython->deeplabcut==2.2.0.1) (4.4.2)
Collecting decorator
  Downloading decorator-5.0.9-py3-none-any.whl (8.9 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from jedi>=0.16->ipython->deeplabcut==2.2.0.1) (0.8.2)
Requirement already satisfied: wcwidth in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->deeplabcut==2.2.0.1) (0.2.5)
Requirement already satisfied: imageio-ffmpeg>=0.2.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from moviepy->deeplabcut==2.2.0.1) (0.4.5)
Requirement already satisfied: proglog<=1.0.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from moviepy->deeplabcut==2.2.0.1) (0.1.9)
Collecting llvmlite<0.38,>=0.37.0rc1
  Using cached llvmlite-0.37.0-cp38-cp38-win_amd64.whl (17.0 MB)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from scikit-learn->deeplabcut==2.2.0.1) (2.2.0)
Requirement already satisfied: joblib>=0.11 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from scikit-learn->deeplabcut==2.2.0.1) (1.0.1)
Requirement already satisfied: numexpr>=2.6.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tables->deeplabcut==2.2.0.1) (2.7.3)
Requirement already satisfied: msgpack>=0.5.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorpack->deeplabcut==2.2.0.1) (1.0.2)
Requirement already satisfied: psutil>=5 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorpack->deeplabcut==2.2.0.1) (5.8.0)
Requirement already satisfied: pyzmq>=16 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorpack->deeplabcut==2.2.0.1) (22.2.1)
Requirement already satisfied: tabulate>=0.7.7 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorpack->deeplabcut==2.2.0.1) (0.8.9)
Requirement already satisfied: msgpack-numpy>=0.4.4.2 in c:\users\brendan.gibbs\anaconda3\envs\deeplabcut1\lib\site-packages (from tensorpack->deeplabcut==2.2.0.1) (0.4.7.1)
Installing collected packages: scipy, grpcio, tensorflow-estimator, llvmlite, keras, h5py, gast, clang, tensorflow, numba
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.32.0
    Uninstalling grpcio-1.32.0:
      Successfully uninstalled grpcio-1.32.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.36.0
    Uninstalling llvmlite-0.36.0:
      Successfully uninstalled llvmlite-0.36.0
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
  Attempting uninstall: gast
    Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1
  Attempting uninstall: numba
    Found existing installation: numba 0.53.1
    Uninstalling numba-0.53.1:
      Successfully uninstalled numba-0.53.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-gpu 2.4.1 requires gast==0.3.3, but you have gast 0.4.0 which is incompatible.
tensorflow-gpu 2.4.1 requires grpcio~=1.32.0, but you have grpcio 1.40.0 which is incompatible.
tensorflow-gpu 2.4.1 requires h5py~=2.10.0, but you have h5py 3.1.0 which is incompatible.
tensorflow-gpu 2.4.1 requires tensorflow-estimator<2.5.0,>=2.4.0, but you have tensorflow-estimator 2.6.0 which is incompatible.
deeplabcut 2.2.0.1 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.
Successfully installed clang-5.0 gast-0.4.0 grpcio-1.40.0 h5py-3.1.0 keras-2.6.0 llvmlite-0.37.0 numba-0.54.0 scipy-1.7.1 tensorflow-2.6.0 tensorflow-estimator-2.6.0

**Comment by bgibWh** [comment]
After that I did `pip install tensorflow_gpu==2.6.0` to resolve the first set of issues but still seems to be a numpy issue when I try training

**Comment by backyardbiomech** [comment]
Numpy didn't update (it knows it needs 1.21 and uses a downloaded version, but doesn't actually update it) based on your log.

`pip install numpy==1.21`

If that doesn't work, sometimes the pip references in an environment can get scrambled after so much fiddling.
Delete your env with `conda env remove -n DEEPLABCUT`

Then download the latest DEEPLABCUT.yaml from GitHub (if you cloned the repo, that one should be good enough).
Open it in a text editor and on the last line replace 

```
"deeplabcut[gui]"
```

with

```
git+https://github.com/deeplabcut/deeplabcut.git
```

Save the file, then use it to create a new env.

**Comment by bgibWh** [comment]
I uninstalled it and changed the YAML file like you said from a cloned version I downloaded today

I created a new environment from that YAML file in anaconda and opened terminal and ran `pip install numpy==1.21` and received the error message `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.6.0 requires numpy~=1.19.2, but you have numpy 1.21.0 which is incompatible.
numba 0.54.0 requires numpy<1.21,>=1.17, but you have numpy 1.21.0 which is incompatible.`

I then went to ipython and ran `import deeplabcut` and got this:

DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)

ImportError                               Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\__init__.py in <module>
     44
     45
---> 46 from deeplabcut.create_project import (
     47     create_new_project,
     48     create_new_project_3d,

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\create_project\__init__.py in <module>
      1 from deeplabcut.create_project.add import add_new_videos
----> 2 from deeplabcut.create_project.demo_data import load_demo_data
      3 from deeplabcut.create_project.modelzoo import (
      4     create_pretrained_human_project,
      5     create_pretrained_project,

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\create_project\demo_data.py in <module>
     13
     14 import deeplabcut
---> 15 from deeplabcut.utils import auxiliaryfunctions
     16
     17

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\utils\__init__.py in <module>
----> 1 from deeplabcut.utils.auxfun_multianimal import *
      2 from deeplabcut.utils.auxfun_videos import *
      3 from deeplabcut.utils.auxiliaryfunctions import *
      4 from deeplabcut.utils.conversioncode import *
      5 from deeplabcut.utils.frameselectiontools import *

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py in <module>
     18
     19 from deeplabcut.utils import auxiliaryfunctions
---> 20 from deeplabcut.generate_training_dataset import trainingsetmanipulation
     21
     22 def extractindividualsandbodyparts(cfg):

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py in <module>
     10
     11 from deeplabcut.generate_training_dataset.frame_extraction import *
---> 12 from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
     13 from deeplabcut.generate_training_dataset.multiple_individuals_trainingsetmanipulation import *

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py in <module>
     21 import yaml
     22
---> 23 from deeplabcut.pose_estimation_tensorflow import training
     24 from deeplabcut.utils import (
     25     auxiliaryfunctions,

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py in <module>
     18 from deeplabcut.pose_estimation_tensorflow.models import *
     19 from deeplabcut.pose_estimation_tensorflow.nnets import *
---> 20 from deeplabcut.pose_estimation_tensorflow.predict_videos import *
     21 from deeplabcut.pose_estimation_tensorflow.training import *
     22 from deeplabcut.pose_estimation_tensorflow.util import *

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in <module>
     31 from deeplabcut.pose_estimation_tensorflow.config import load_config
     32 from deeplabcut.pose_estimation_tensorflow.core import predict
---> 33 from deeplabcut.pose_estimation_tensorflow.lib import inferenceutils, trackingutils
     34 from deeplabcut.utils import auxiliaryfunctions, auxfun_multianimal
     35

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\trackingutils.py in <module>
     35 from filterpy.kalman import KalmanFilter
     36 from matplotlib import patches
---> 37 from numba import jit
     38 from numba.core.errors import NumbaPerformanceWarning
     39 from scipy.optimize import linear_sum_assignment

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\numba\__init__.py in <module>
    196
    197 _ensure_llvm()
--> 198 _ensure_critical_deps()
    199
    200 # we know llvmlite is working as the above tests passed, import it now as SVML

~\Anaconda3\envs\DEEPLABCUT1\lib\site-packages\numba\__init__.py in _ensure_critical_deps()
    136         raise ImportError("Numba needs NumPy 1.17 or greater")
    137     elif numpy_version > (1, 20):
--> 138         raise ImportError("Numba needs NumPy 1.20 or less")
    139
    140     try:

ImportError: Numba needs NumPy 1.20 or less

**Comment by nataliekoh** [comment]
Hi all, I am encountering the same problem as bgibWh but I see this issue is closed - is there a solution?
