### ISSUE TITLE
FileNotFoundError [Win 32 Error] File Specified Not Found

### ISSUE THREAD

**Issue by v-moore** [DeepLabCut/DeepLabCut#2154]
- [x] I have searched the existing issues

### Error description

When running 3D DLC, I'm able not able to create the video output following the deeplabcut.create_labeled_video_3d command, instead receive FileNotFoundError: [WinError 2] The system cannot find the file specified. In looking through other issues, it seems it would either be a problem with the config file pathways or an FFmpeg installation issue. I've attempted to install or access FFmpeg in different ways, such as installing it in the anaconda prompt with, "conda create -n newenv -c conda-forge ffmpeg, which is successful, but then isn't accessed when I change to the python environment in the anaconda prompt. I've also attempted to add FFmpeg to the root path of the computer, but this hasn't worked either.  When running 2D DLC this hasn't been a problem, so I'm uncertain what the correct way is to set-up FFmpeg so it is accessible in 3D DLC. I apologize if this is not formatted correctly. Thanks for any help with this! 

### Operating System

Windows 10 Enterprise, 64-bit operating system, x64-based processor

### DeepLabCut version

dlc version - __version__ = "2.2b6"
VERSION = __version__

### DeepLabCut mode

3d

### Device type

CPU - Intel(R) Xeon(R) CPU E5-1603 v3 @ 2.80GHz   2.80 GHz
GPU - NVIDIA GeForce GTX 1060 6 GB

### Steps To Reproduce

1. open anaconda cmd prompt
2. type "conda activate DLC-GPU'
3. type "python"
4. type "import deeplabcut"
5. type "import os"
6. set directory to save project to, "os.chdir("C:/Users/Sylwestrak Lab/Desktop/3D DLC")
7. Set up experiment
8. YourName='Vincent'
9. YourExperimentName='3D-test'
10. config_path = deeplabcut.create_new_project_3d(YourExperimentName, YourName, num_cameras=2)
11.  Edit config file to include 3D skeleton matching 2d config files
12. Edit config file to include pathway to 2d config files
13. Cameras previously calibrated
14. Set video_path to folder with videos to analyze, video_path='C:/Users/Sylwestrak Lab/Desktop/m1772 videos'
15. Triangulate video, "deeplabcut.triangulate(config_path,video_path, videotype='mp4')"
16. Create labeled video, "deeplabcut.create_labeled_video_3d(config_path, ['C:/Users/Sylwestrak Lab/Desktop/m1772 videos'], start=50, end=250,videofolder=video_path,videotype='.mp4')"
17. 

### Relevant log output

```shell
(base) C:\Users\Sylwestrak Lab>conda activate DLC-GPU

(DLC-GPU) C:\Users\Sylwestrak Lab>python
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
>>> import os
>>> import subprocess
>>> os.chdir("C:/Users/Sylwestrak Lab/Desktop/3D DLC")
>>> os.getcwd()
'C:\\Users\\Sylwestrak Lab\\Desktop\\3D DLC'
>>> YourName='Vincent'
>>> YourExperimentName='3D-test'
>>> config_path = deeplabcut.create_new_project_3d(YourExperimentName, YourName, num_cameras=2)
Created "C:\Users\Sylwestrak Lab\Desktop\3D DLC\3D-test-Vincent-2023-02-10-3d\camera_matrix"
Created "C:\Users\Sylwestrak Lab\Desktop\3D DLC\3D-test-Vincent-2023-02-10-3d\calibration_images"
Created "C:\Users\Sylwestrak Lab\Desktop\3D DLC\3D-test-Vincent-2023-02-10-3d\undistortion"
Created "C:\Users\Sylwestrak Lab\Desktop\3D DLC\3D-test-Vincent-2023-02-10-3d\corners"
Generated "C:\Users\Sylwestrak Lab\Desktop\3D DLC\3D-test-Vincent-2023-02-10-3d\config.yaml"

A new project with name 3D-test-Vincent-2023-02-10-3d is created at C:\Users\Sylwestrak Lab\Desktop\3D DLC and a configurable file (config.yaml) is stored there. If you have not calibrated the cameras, then use the function 'calibrate_camera' to start calibrating the camera otherwise use the function ``triangulate`` to triangulate the dataframe
>>> video_path='C:/Users/Sylwestrak Lab/Desktop/video folder'
>>> os.listdir(video_path)
['m1772_camera-1.mp4', 'm1772_camera-2.mp4']
>>> deeplabcut.triangulate(config_path,video_path, videotype='mp4')
List of pairs: [['C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-2.mp4']]
Analyzing video C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-1.mp4 using config_file_camera-1
Using snapshot-10300 for model C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1
Initializing ResNet
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
Starting to analyze %  C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-1.mp4
Loading  C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-1.mp4
Duration of video [s]:  909.95 , recorded with  20.0 fps!
Overall # of frames:  18199  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
18281it [08:57, 33.62it/s]                                                                                             Detected frames:  18199
18281it [09:00, 33.81it/s]
Saving results in C:\Users\Sylwestrak Lab\Desktop\video folder...
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!
C:\Users\Sylwestrak Lab\Desktop\video folder m1772_camera-1 DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300
Filtering with median model C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-1.mp4
4it [00:00, 34.24it/s]
Saving filtered csv poses!
Analyzing video C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-2.mp4 using config_file_camera-2
Using snapshot-10300 for model C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1
Initializing ResNet
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
Starting to analyze %  C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-2.mp4
Loading  C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-2.mp4
Duration of video [s]:  909.95 , recorded with  20.0 fps!
Overall # of frames:  18199  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
18281it [08:56, 33.30it/s]                                                                                             Detected frames:  18199
18281it [08:59, 33.89it/s]
Saving results in C:\Users\Sylwestrak Lab\Desktop\video folder...
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!
C:\Users\Sylwestrak Lab\Desktop\video folder m1772_camera-2 DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300
Filtering with median model C:/Users/Sylwestrak Lab/Desktop/video folder\m1772_camera-2.mp4
4it [00:00, 42.12it/s]
Saving filtered csv poses!
Undistorting...
4it [00:00, 60.62it/s]
Computing the triangulation...
Triangulated data for video ['C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-2.mp4']
Results are saved under:  C:\Users\Sylwestrak Lab\Desktop\video folder
All videos were analyzed...
Now you can create 3D video(s) using deeplabcut.create_labeled_video_3d
>>> deeplabcut.create_labeled_video_3d(config_path, ['video_path='C:/Users/Sylwestrak Lab/Desktop/video folder'], start=50, end=250,videofolder=video_path,videotype='.mp4')
  File "<stdin>", line 1
    deeplabcut.create_labeled_video_3d(config_path, ['video_path='C:/Users/Sylwestrak Lab/Desktop/video folder'], start=50, end=250,videofolder=video_path,videotype='.mp4')
                                                                  ^
SyntaxError: invalid syntax
>>> deeplabcut.create_labeled_video_3d(config_path, ['video_path=C:/Users/Sylwestrak Lab/Desktop/video folder'], start=50, end=250,videofolder=video_path,videotype='.mp4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 96, in create_labeled_video_3d
    file_list = auxiliaryfunctions_3d.Get_list_of_triangulated_and_videoFiles(path,videotype,scorer_3d,cam_names,videofolder)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\auxiliaryfunctions_3d.py", line 165, in Get_list_of_triangulated_and_videoFiles
    triangulated_folder = triangulated_folder[0]
IndexError: list index out of range
>>> deeplabcut.create_labeled_video_3d(config_path, ['C:/Users/Sylwestrak Lab/Desktop/video folder'], start=50, end=250,videofolder=video_path,videotype='.mp4')
Analyzing all the videos in the directory
[['C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_DLC_3D.h5', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-2.mp4']]
Creating 3D video from m1772_camera-1.mp4 and m1772_camera-2.mp4 using m1772_DLC_3D.h5
Looking for filtered predictions...
Found the following filtered data:  C:\Users\Sylwestrak Lab\Desktop\video folder\*m1772_camera-1DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5 C:\Users\Sylwestrak Lab\Desktop\video folder\*m1772_camera-2DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5
100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [02:56<00:00,  1.13it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 152, in create_labeled_video_3d
    subprocess.call(['ffmpeg', '-start_number', str(start) ,'-framerate', str(30), '-i', str('img%0'+str(num_frames)+'d.png'), '-r', str(30),'-vb', '20M' ,os.path.join(output_folder,str('../'+file_name+'.mpg'))])
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> deeplabcut.create_labeled_video_3d(config_path, ['C:/Users/Sylwestrak Lab/Desktop/video folder'], start=50, end=250,videofolder=video_path,videotype='.mp4')
Analyzing all the videos in the directory
[['C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_DLC_3D.h5', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-2.mp4']]
Creating 3D video from m1772_camera-1.mp4 and m1772_camera-2.mp4 using m1772_DLC_3D.h5
Looking for filtered predictions...
Found the following filtered data:  C:\Users\Sylwestrak Lab\Desktop\video folder\*m1772_camera-1DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5 C:\Users\Sylwestrak Lab\Desktop\video folder\*m1772_camera-2DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5
100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [02:53<00:00,  1.15it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 152, in create_labeled_video_3d
    subprocess.call(['ffmpeg', '-start_number', str(start) ,'-framerate', str(30), '-i', str('img%0'+str(num_frames)+'d.png'), '-r', str(30),'-vb', '20M' ,os.path.join(output_folder,str('../'+file_name+'.mpg'))])
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> deeplabcut.create_labeled_video_3d(config_path, ['C:/Users/Sylwestrak Lab/Desktop/video folder'], start=50, end=250,videofolder=video_path,videotype='.mp4')
Analyzing all the videos in the directory
[['C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_DLC_3D.h5', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/video folder\\m1772_camera-2.mp4']]
Creating 3D video from m1772_camera-1.mp4 and m1772_camera-2.mp4 using m1772_DLC_3D.h5
Looking for filtered predictions...
Found the following filtered data:  C:\Users\Sylwestrak Lab\Desktop\video folder\*m1772_camera-1DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5 C:\Users\Sylwestrak Lab\Desktop\video folder\*m1772_camera-2DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5
100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [03:04<00:00,  1.09it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 152, in create_labeled_video_3d
    subprocess.call(['ffmpeg', '-start_number', str(start) ,'-framerate', str(30), '-i', str('img%0'+str(num_frames)+'d.png'), '-r', str(30),'-vb', '20M' ,os.path.join(output_folder,str('../'+file_name+'.mpg'))])
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>> video_path='C:/Users/Sylwestrak Lab/Desktop/m1772 videos'
>>> os.listdir(video_path)
['m1772_camera-1.mp4', 'm1772_camera-2.mp4']
>>> deeplabcut.triangulate(config_path,video_path, videotype='mp4')
List of pairs: [['C:/Users/Sylwestrak Lab/Desktop/m1772 videos\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/m1772 videos\\m1772_camera-2.mp4']]
Analyzing video C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-1.mp4 using config_file_camera-1
Using snapshot-10300 for model C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1
Initializing ResNet
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
Starting to analyze %  C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-1.mp4
Loading  C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-1.mp4
Duration of video [s]:  909.95 , recorded with  20.0 fps!
Overall # of frames:  18199  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
18281it [08:50, 33.98it/s]                                                                                             Detected frames:  18199
18281it [08:53, 34.25it/s]
Saving results in C:\Users\Sylwestrak Lab\Desktop\m1772 videos...
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!
C:\Users\Sylwestrak Lab\Desktop\m1772 videos m1772_camera-1 DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300
Filtering with median model C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-1.mp4
4it [00:00, 43.04it/s]
Saving filtered csv poses!
Analyzing video C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-2.mp4 using config_file_camera-2
Using snapshot-10300 for model C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1
Initializing ResNet
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
INFO:tensorflow:Restoring parameters from C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\dlc-models\iteration-0\20230203_DLC_m1772Feb3-trainset95shuffle1\train\snapshot-10300
Starting to analyze %  C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-2.mp4
Loading  C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-2.mp4
Duration of video [s]:  909.95 , recorded with  20.0 fps!
Overall # of frames:  18199  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
18281it [08:54, 33.72it/s]                                                                                             Detected frames:  18199
18281it [08:57, 34.00it/s]
Saving results in C:\Users\Sylwestrak Lab\Desktop\m1772 videos...
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!
C:\Users\Sylwestrak Lab\Desktop\m1772 videos m1772_camera-2 DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300
Filtering with median model C:/Users/Sylwestrak Lab/Desktop/m1772 videos\m1772_camera-2.mp4
4it [00:00, 42.13it/s]
Saving filtered csv poses!
Undistorting...
4it [00:00, 66.70it/s]
Computing the triangulation...
Triangulated data for video ['C:/Users/Sylwestrak Lab/Desktop/m1772 videos\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/m1772 videos\\m1772_camera-2.mp4']
Results are saved under:  C:\Users\Sylwestrak Lab\Desktop\m1772 videos
All videos were analyzed...
Now you can create 3D video(s) using deeplabcut.create_labeled_video_3d
>>> deeplabcut.create_labeled_video_3d(config_path, ['C:/Users/Sylwestrak Lab/Desktop/m1772 videos'], start=50, end=250,videofolder=video_path,videotype='.mp4')
Analyzing all the videos in the directory
[['C:/Users/Sylwestrak Lab/Desktop/m1772 videos\\m1772_DLC_3D.h5', 'C:/Users/Sylwestrak Lab/Desktop/m1772 videos\\m1772_camera-1.mp4', 'C:/Users/Sylwestrak Lab/Desktop/m1772 videos\\m1772_camera-2.mp4']]
Creating 3D video from m1772_camera-1.mp4 and m1772_camera-2.mp4 using m1772_DLC_3D.h5
Looking for filtered predictions...
Found the following filtered data:  C:\Users\Sylwestrak Lab\Desktop\m1772 videos\*m1772_camera-1DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5 C:\Users\Sylwestrak Lab\Desktop\m1772 videos\*m1772_camera-2DLC_resnet50_20230203_DLC_m1772Feb3shuffle1_10300*filtered.h5
100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [02:50<00:00,  1.17it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 152, in create_labeled_video_3d
    subprocess.call(['ffmpeg', '-start_number', str(start) ,'-framerate', str(30), '-i', str('img%0'+str(num_frames)+'d.png'), '-r', str(30),'-vb', '20M' ,os.path.join(output_folder,str('../'+file_name+'.mpg'))])
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### Anything else?

3D config file
 Project definitions (do not edit)
Task: 3D-test
scorer: Vincent
date: Feb10

Project path (change when moving around)
project_path: C:\Users\Sylwestrak Lab\Desktop\3D DLC\3D-test-Vincent-2023-02-10-3d

Plotting configuration
skeleton:     # Note that the pairs must be defined, as you want them linked!

- - nose
  - implant

- - implant
  - center of mass

- - center of mass
  - tail

skeleton_color: black
pcutoff: 0.4
colormap: jet
dotsize: 15
alphaValue: 0.8
markerType: '*'
markerColor: r

Number of cameras, camera names, path of the config files, shuffle index and trainingsetindex used to analyze videos:
num_cameras: 2
camera_names:
- camera-1
- camera-2
scorername_3d: DLC_3D # Enter the scorer name for the 3D output
config_file_camera-1: C:\\Users\\Sylwestrak Lab\\Desktop\\DLC\\20230203_DLC_m1772-Vincent-2023-02-03\\camera-1.yaml
config_file_camera-2: C:\\Users\\Sylwestrak Lab\\Desktop\\DLC\\20230203_DLC_m1772-Vincent-2023-02-03\\camera-2.yaml
shuffle_camera-1: 1
trainingsetindex_camera-1: 0
shuffle_camera-2: 1
trainingsetindex_camera-2: 0

2D config file

Project definitions (do not edit)
Task: 20230203_DLC_m1772
scorer: Vincent
date: Feb3

Project path (change when moving around)
project_path: C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03

 Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\videos\m1772_camera-2.mp4:
    crop: 0, 640, 0, 480
  C:\Users\Sylwestrak Lab\Desktop\DLC\20230203_DLC_m1772-Vincent-2023-02-03\videos\m1772_camera-1.mp4:
    crop: 0, 640, 0, 480
bodyparts:
- nose
- implant
- center of mass
- tail
start: 0
stop: 1
numframes2pick: 20

Plotting configuration
skeleton:
- - nose
  - implant
- - implant
  - center of mass
- - center of mass
  - tail
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: jet

Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
resnet:
snapshotindex: -1
batch_size: 8

Cropping Parameters (for analysis and outlier frame detection)
cropping: false
#if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
default_net_type: resnet_50
default_augmenter: default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @v-moore, could you try to update DLC to at least 2.2.3 with `pip install deeplabcut==2.2.3`? The version you use is 2.5 years old and the 3D code has been fixed in multiple places since then ☺️

**Comment by 1345602573** [comment]
I am using version 2.2.3, and I have the same problem

**Comment by jeylau** [comment]
Judging from this [thread](https://stackoverflow.com/questions/45131495/the-system-cannot-find-the-file-specified-with-ffmpeg), running `conda install ffmpeg` is the solution. Note though that when installing deeplabcut through the provided conda environment file, it is bundled with ffmpeg, so you're guaranteed to have a working ffmpeg installation. Please reopen the issue or let us know if you're still facing problems 😊

**Comment by 1345602573** [comment]
> Judging from this [thread](https://stackoverflow.com/questions/45131495/the-system-cannot-find-the-file-specified-with-ffmpeg), running `conda install ffmpeg` is the solution. Note though that when installing deeplabcut through the provided conda environment file, it is bundled with ffmpeg, so you're guaranteed to have a working ffmpeg installation. Please reopen the issue or let us know if you're still facing problems 😊

Thank you very much for your reply. I have already experimented with your method and the problem has not been resolved. However, I found that if I did not check the "create a higher quality video" option, I can use it normally

**Comment by twheatcroft07** [comment]
@jeylau I have the same error, and installing ffmpeg didn't solve it. @1345602573, is that an option with the GUI version? I can't see that option as an input to this function https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html#visualize-your-3d-deeplabcut-videos

***EDIT***

The below worked for me ->
pip uninstall ffmpeg
pip uninstall ffmpeg-python
conda install ffmpeg
