### ISSUE TITLE
Error message AttributeError: 'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by ckKLI** [DeepLabCut/DeepLabCut#611]
OS: Windows 10
env Anaconda3
DeepLabCut Version 2.1.6.2
Browser Mozilla Firefox

Problem:
I used the DeepLabCut Project Manager GUI. Everything works fine until I try to extract outlier frames. Every time I try this I get the error message AttributeError: 'DataFrame' object has no attribute 'ix'. I already tried to install pandas 0.25.1 (conda install pandas==0.25.1). I also removed the newest version of Anaconda3 from my sytem and installed an older one. But this did not solve the problem. Could you please help me with this? Note that I am an absolute beginner to Anaconda, Python and the whole stuff. 

1) In [3]: deeplabcut.launch_dlc()
2) in DeepLabCut Project Manager GUI go to Extract outlier frames
3) choose manual for specify the algorithm
4) click Ok
5) in the opening window click grab frames
```

Error Message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frame_extraction_toolbox.py in grabFrame(self, event)
    360         else:
    361             self.vid.set(1,self.currFrame)
--> 362             self.chooseFrame()
    363
    364

D:\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frame_extraction_toolbox.py in chooseFrame(self)
    320         self.machinefile = os.path.join(str(output_path),'machinelabels-iter'+str(self.iterationindex)+'.h5')
    321         name = str(fname.stem)
--> 322         DF = self.Dataframe.ix[[self.currFrame]]
    323         DF.index=[os.path.join('labeled-data',name,"img"+str(index).zfill(self.strwidth)+".png") for index in DF.index]
    324         img_name = str(output_path) +'/img'+str(self.currFrame).zfill(int(np.ceil(np.log10(self.numberFrames)))) + '.png'

D:\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5272             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5273                 return self[name]
-> 5274             return object.__getattribute__(self, name)
   5275
   5276     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'ix'


```

**Comment by jeylau** [comment]
This is odd. 'ix' has only been removed in pandas 1.0.0, so reverting to earlier pandas versions should work. Could you double check your pandas version? I also think that the command takes only an equal sign: `conda install pandas=0.25.1`

**Comment by MMathisLab** [comment]
< pandas 1 should work, but we also just fixed this in the code @AlexEMG - but it's likely not in the pypi release yet (one would have to install from github source right now). But, in short, this will go away in the next pypi update :)

**Comment by AlexEMG** [comment]
I did test backwards compatibility with pandas 0.23 or so. What version do you have?

**Comment by ckKLI** [comment]
I reinstalled Anaconda3 and DeepLabCut from github source. Then I updated pandas, but I still get the same error message when I try to extract outlier frames. My pandas version is 1.0.1. I am a little bit frustrated. DeepLabCut would safe me a lot of time analyzing my data :(

**Comment by ckKLI** [comment]
I tried extraction of outlier frames by typing the command in the terminal instead of using the Project Manager GUI. Know the extraction is working. I am so glad about this :)

**Comment by MMathisLab** [comment]
I am confused too; as looking at your code error, it is using this function:
`\deeplabcut\refine_training_dataset\outlier_frame_extraction_toolbox.py`

it is looking at line # 322

`322         DF = self.Dataframe.ix[[self.currFrame]]` 

where this is an `.ix`, which is supported in pre-pandas 1, i.e you need to install `pip install pandas==0.25`. BUT, we fixed this already in the latest update. i.e. this does not exist in the current code:

https://github.com/AlexEMG/DeepLabCut/blob/7bd99207f9dfdb6f33625a4c557b0872fef3dd66/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py#L322

So, you must be using an older version of deeplabcut, but then updating pandas, which would not work.

**Comment by MMathisLab** [comment]
So, the solution is as follows:

(1) install the base code by:

`git clone https://github.com/AlexEMG/DeepLabCut`

cd into DeepLabCut 

Then run:
```
import deeplabcut

deeplabcut.__version__

deeplabcut.__file__ 
```

OR (2) install deeplabcut, and DO not upgrade pandas. You need to be sure an older version is installed. to check this:
```
import pandas
pandas.__version__
```

**Comment by ckKLI** [comment]
First I tried step 1 as you described it. DeepLabCut version was 2.1.6.2 and pandas 1.0.1. Interestingly I still got the same error code.
![DeepLabCut2](https://user-images.githubusercontent.com/61821473/76115539-a005af80-5fe8-11ea-8dd8-c13305a0ad7d.JPG)
Then I downgraded pandas to version 0.25.1 and checked the installed version with the command "conda list". I still get this error message. I am also confused. This seems illogical to me. I just don't know what I'm doing wrong.

**Comment by MMathisLab** [comment]
can you please post the output of: 

```
import pandas
pandas.__version__
```

**Comment by ckKLI** [comment]
I tried again to install pandas 0.25.1. The same way as I did before and it is WORKING :) I don't know why it didn't work the first time. You can't imagine how happy I am. Thank you for your help and your rapid answers. DeepLabCut is such a great software and saves so much time in data analysis. Thank you for offering it as an open source software :)

**Comment by xcccc402** [comment]
I had same issue. it seems I am using the latest version of DLP and pandas. What is the solution except downgrade pandas. 

<img width="991" alt="Screenshot 2020-03-23 at 20 03 37" src="https://user-images.githubusercontent.com/62570054/77358263-6e5b4b00-6d41-11ea-834b-cd8821cfe7e8.png">

**Comment by jeylau** [comment]
xcccc402, the first part of this answer from @MMathisLab should help you:
> So, the solution is as follows:
> 
> (1) install the base code by:
> 
> `git clone https://github.com/AlexEMG/DeepLabCut`
> 
> cd into DeepLabCut
> 
> Then run:
> 
> ```
> import deeplabcut
> 
> deeplabcut.__version__
> 
> deeplabcut.__file__ 
> ```

**Comment by MMathisLab** [comment]
Also deeplabcut was just updated last night, so you should be able to just run `pip install deeplabcut==2.1.6.3`

**Comment by hafez-ahmad** [comment]
DataFrame' object has no attribute 'ix'

**Comment by MMathisLab** [comment]
pip install deeplabcut==2.1.6.4

**Comment by bahaou** [comment]
use .iloc instead of .ix

**Comment by AlexEMG** [comment]
@hafez-ahmad and @bahaou -- ideally also use pandas 1.*

**Comment by moschjoon** [comment]
Either try .iloc[] instead of using .ix[] which is deprecated or Do conda install pandas==0.25.1

**Comment by Dave-Vedant** [comment]
Use data.iloc() instead of data.ix() ---- > package is updated

**Comment by YerraNaveen** [comment]
> Either try .iloc[] instead of using .ix[] which is deprecated or Do conda install pandas==0.25.1

where should i do this #conda install pandas==0.25.1

**Comment by AlexEMG** [comment]
In the anaconda prompt, in the environment where Deeplabcut is installed

More info: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html


________________________________

**Comment by Ekta-Agnihotri** [comment]
use 'iloc' instead of 'ix' e.g. data.iloc[:5,:3]
More Info: https://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix/

**Comment by AlexEMG** [comment]
We deprecated .ix for .iloc and now require at least pandas 1.0

Dear EKta,

I’m not clear what you are pointing out?

Alexander


________________________________

**Comment by advmsbrdn** [comment]
Hi sir. I am using GUI deeplabcut on window 10. When refining tracklet this kind of error happened. Do you have any idea to solve it?


Traceback (most recent call last):
  File "C:\Users\adam\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\refine_tracklets.py", line 318, in create_tracks
    n_tracks=self.ntracks.GetValue(),
  File "C:\Users\adam\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 1042, in stitch_tracklets
    pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals
  File "C:\Users\adam\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 510, in from_pickle
    tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
  File "C:\Users\adam\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 528, in from_dict_of_dict
    inds, data = zip(*[(cls.get_frame_ind(k), v) for k, v in dict_.items()])
AttributeError: 'list' object has no attribute 'items'

**Comment by jeylau** [comment]
Hi @advmsbrdn, are you sure it is a _bx. or _el.pickle that is selected in the GUI?
