### ISSUE TITLE
ScannerError: mapping values are not allowed

### ISSUE THREAD

**Issue by neuropsycher** [DeepLabCut/DeepLabCut#776]
Hello, I have been running DeepLabCut through Google Colab and can get all the way to analyzing the video, the point where I get errors. I first received an error telling me to check video path and now it is stuck on ScannerError. Any help would be greatly appreciated! Thank you for your time.

![config](https://user-images.githubusercontent.com/64938386/86199167-01fd9e00-bb1f-11ea-89b3-14df67450480.PNG)
![analyze issue colab](https://user-images.githubusercontent.com/64938386/86199168-02963480-bb1f-11ea-94cf-f0fe011e324c.PNG)

**Comment by jeylau** [comment]
Hello @neuropsycher, could you re-try after fixing the missing slash before your video path, as well as the indentation?
'video_sets' should rather look like:
```
video_sets:
    /content/My Drive/etc/myvideo.mp4:
        crop: 0, 400, 0, 400
```
Note the tab at each line 😃

**Comment by neuropsycher** [comment]
Hi @jeylau , thank you so much for your advice. I tried a few times moving things around as you suggested. I attached a picture of the config file that finally allowed me to get a better looking output, but it is saying there is no video found. In the folder I supplied, I have made sure there my video is in there. I know in Google Colab, it mentions that a "new video" is made, so should I be changing my video file path?

Additionally, if I continue on and get to the create labeled video, it is also not outputting anything which of course makes sense if no video is found to analyze.  

Thank you so much for your time!

![new issue analyzing](https://user-images.githubusercontent.com/64938386/86274578-82f87c00-bb97-11ea-842e-dedd5106ba84.PNG)
![fixed config](https://user-images.githubusercontent.com/64938386/86274585-85f36c80-bb97-11ea-8a3b-21f7801188fa.PNG)

**Comment by jeylau** [comment]
'crop' still does not look right to me, but I'm happy python does not complain about it 😄 It should be right a line below your video path, and with another level of indentation.
Also, are you certain the video is outside your project folder? I would have expected it to be within `Trial3test-Heather-2020-06-30/videos/`

**Comment by neuropsycher** [comment]
It's very weird. When I make that change with the crop, being directly one line below and one more indentation, it gives another ScannerError. However, I know I did have my video in a weird place. I made sure to upload to the videos folder under my project folder and update the config file accordingly and I get the same output that the video cannot be found. 

I'm not a computer science person, but could this be because there are multiple animals in my video but I only chose to label one (I'm just trying to test things out on our own behavioral videos before running it more seriously)?

**Comment by neuropsycher** [comment]
@jeylau thank you so much again for your help! I wanted to update and say I figured it out. Actually a very careless mistake of editing a portion not meant to be edited, but your suggestions were very helpful and definitely a part of the problem too.
